version: '3.1'
services:
    php-apache:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html
            - /etc/ssl/certs
        depends_on:
            - mysql
        
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8000:80
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PASSWORD=password
            - PMA_USER=root
            - MYSQL_USER=gdsm
            - MYSQL_PASSWORD=password
